### ISSUE TITLE
Show some "progressbar" while loading terms

### ISSUE THREAD

**Issue by yarikoptic** [NIDM-Terms/nidm-terms.github.io#38]
Opening https://nidm-terms.github.io/index.html? left me with 
![image](https://user-images.githubusercontent.com/39889/127696386-063b5e81-41c2-4aa6-9a56-948ab8dd0ed4.png)

for a good number of seconds (may be because Zoom meanwhile was making everything slower), so I thought that may be no terms are yet "Available"?  Showing some spinning horizontal or circular "progress" gif, and replacing it with actual content whenever ready would provide user a feedback preventing similar confusion

**Comment by nqueder** [comment]
Hi @yarikoptic, 

Thank you so much for the feedback and suggestions! We're working on fixing this issue and improving the speed of the available terms page. Changes will be merged within the next few days.
