### ISSUE TITLE
suggestion: rename top level item from "available" to "browse"  

### ISSUE THREAD

**Issue by robertoostenveld** [NIDM-Terms/nidm-terms.github.io#50]
I propose to rename the "Available Terms" button to "Browse Terms". That expresses the action (to browse) which is in line with the actions on the other buttons (to export, to add, ...)

**Comment by nqueder** [comment]
Thanks for the suggestion! 

“Available terms” has now been changed to “Browse Terms”.  The change is now reflected on [nidm-terms.github.io](nidm-term.github.io).
